name: Prettier & ESLint

on: [pull_request]
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.16.0]
        
    steps:    
    - uses: actions/checkout@v3
    - name: Run prettier
      run: npm run prettier
    - name: Run eslint
      run: npm run lint
