name: Prettier & ESLint

on: [pull_request]
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.16.0]
        
    steps:    
    - uses: actions/checkout@v3
    - name: Install 
      run: npm ci
    - name: Run prettier:check
      run: npm run prettier:check
    - name: Run eslint:check
      run: npm run lint:check
